name: 'PHP_CodeSniffer Annotations'
description: 'Commit and Pull Request annotations for PHP Code Sniffer rulesets'
author: 'Navarr Barnier'
inputs:
  enable_warnings:
    description: 'Enable checking for warnings (-w)'
    required: false
    default: ''
  phpcs_bin_path:
    description: 'Path to phpcs binary'
    required: false
    default: 'vendor/bin/phpcs'
  installed_paths:
    description: 'Setting the installed standard paths'
    required: false
    default: ''
  only_changed_files:
    description: 'Run linter on changed files only'
    required: false
    default: ''
  only_changed_lines:
    description: 'Report errors only for changed lines'
    required: false
    default: ''
  token:
    description: >
      GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow. This input
      is used to pass the secret to the workflow.

      [For more information reference this docs page](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token)

    required: false
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
  - run: bash ${{ github.action_path }}/entrypoint.sh
    shell: bash
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}
      INPUT_ONLY_CHANGED_FILES: ${{ inputs.only_changed_files }}
      INPUT_TOKEN: ${{ inputs.token }}
      INPUT_ONLY_CHANGED_LINES: ${{ inputs.only_changed_lines }}
      INPUT_INSTALLED_PATHS: ${{ inputs.installed_paths }}
      INPUT_PHPCS_BIN_PATH: ${{ inputs.phpcs_bin_path }}
      INPUT_ENABLE_WARNINGS: ${{ inputs.enable_warnings }}
branding:
  icon: 'zap'
  color: 'purple'
